spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/memo_app_ogata
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    properties:
      javax:
        persistence:
          validation:
            mode: none

